from __future__ import annotations

from typing import Protocol

from puripuly_heart.domain.models import OSCMessage


class OscSender(Protocol):
    def send_chatbox(self, text: str) -> None: ...
    def send_typing(self, is_typing: bool) -> None: ...


class OscSink(Protocol):
    def enqueue(self, message: OSCMessage) -> None: ...
    def send_immediate(self, text: str) -> bool: ...
    def send_typing(self, is_typing: bool) -> None: ...
    def set_typing_reason(self, reason: str, active: bool) -> None: ...
    def clear_typing_reasons(self) -> None: ...
    def process_due(self) -> None: ...
