"""Protocol definitions for overlay state modules.

Each Protocol defines the public API of an overlay module.
Modules depend on Protocols (hexagonal architecture), not on concrete implementations.
OverlayPresentationState (composition root) creates concrete implementations and wires them via DI.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Protocol, runtime_checkable
from uuid import UUID

if TYPE_CHECKING:
    from puripuly_heart.domain.overlay_types import (
        OverlayEntryKey,
        OverlayLogicalTurnEntry,
        OverlayPresentationBlock,
        OverlayTurnDecisionRecord,
    )


@runtime_checkable
class EntryStoreProtocol(Protocol):
    """Public API of EntryStore — entry storage and lifecycle."""

    entries: dict  # OverlayEntryKey → OverlayLogicalTurnEntry

    def entry_for(self, channel: str | None, utterance_id: UUID | None, entry_factory: type) -> object: ...
    @staticmethod
    def entry_key(channel: str | None, utterance_id: UUID | None) -> OverlayEntryKey: ...
    def live_turn_key_for_channel(self, channel: str) -> tuple | None: ...
    def set_live_turn_key_for_channel(self, channel: str, key: tuple | None) -> None: ...
    def live_entry_for_channel(self, channel: str) -> tuple[tuple, object] | None: ...
    def active_self_overlay_metadata(self) -> object | None: ...
    def remove_entry(self, key: tuple, *, reason: str, now: float | None = ..., tombstone_seq: int | None = ...) -> object | None: ...
    def drain_pending_removals(self) -> list: ...


@runtime_checkable
class SelfEventDispatcherProtocol(Protocol):
    """Public API of SelfEventDispatcher — self channel event handling."""

    def apply_self_active_update(self, event: object, *, now: float, show_translation: bool, terminal_update_reason: object) -> object: ...
    def apply_self_active_clear(self, event: object, *, now: float, show_translation: bool) -> object: ...
    def apply_self_finalized_update(self, event: object, *, now: float, show_translation: bool, next_appearance_seq: object, terminal_update_reason: object) -> object: ...
    def apply_self_translation_update(self, event: object, *, now: float, show_translation: bool, next_appearance_seq: object, terminal_update_reason: object) -> object: ...
    def apply_self_utterance_closed(self, event: object, *, now: float, is_tombstoned: object) -> object: ...


@runtime_checkable
class PeerEventDispatcherProtocol(Protocol):
    """Public API of PeerEventDispatcher — peer channel event handling."""

    def apply_peer_active_update(self, event: object, *, now: float, show_peer_original: bool, next_appearance_seq: object, terminal_update_reason: object) -> object: ...
    def apply_peer_finalized_update(self, event: object, *, now: float, show_peer_original: bool, next_appearance_seq: object, terminal_update_reason: object) -> object: ...
    def apply_peer_translation_update(self, event: object, *, now: float, show_peer_original: bool, next_appearance_seq: object, terminal_update_reason: object) -> object: ...
    def apply_peer_utterance_closed(self, event: object, *, now: float, is_tombstoned: object) -> object: ...


@runtime_checkable
class EventHelpersProtocol(Protocol):
    """Public API of EventHelpers — common reduction helpers."""

    def append_terminal_update_decision(self, terminal_reason: str | None, *, key: tuple, decisions: list) -> bool: ...
    def active_update_entry_or_none(self, *, channel: str, utterance_id: UUID | None, event_seq: int, now: float, show_translation: bool, terminal_update_reason: object, decisions: list) -> tuple[tuple, object] | None: ...
    def active_update_matches_live_payload(self, *, channel: str, key: tuple, entry: object, text: str, secondary_text: str, occupant_key: str, update_id: str | None, origin_wall_clock_ms: int | None, session_scope: str | None, source_text_hash: str | None, source_text_len: int | None, logical_turn_key: str | None) -> bool: ...
    def clear_live_self_pointer(self, *, reason: str, now: float, show_translation: bool) -> None: ...
    def clear_live_peer_pointer(self) -> None: ...
    def refresh_entry_visibility_and_expiration(self, key: tuple, entry: object, *, now: float, publishable_seq: int | None, next_appearance_seq: object, show_peer_original: bool = ..., decisions: list) -> None: ...


@runtime_checkable
class RefreshManagerProtocol(Protocol):
    """Public API of RefreshManager — presentation refresh bursts."""

    def begin_peer_presentation_refresh(self, key: tuple) -> bool: ...
    def tick_peer_presentation_refresh(self, key: tuple) -> bool: ...
    def end_peer_presentation_refresh(self, key: tuple) -> bool: ...
    def begin_self_presentation_refresh(self, key: tuple) -> bool: ...
    def tick_self_presentation_refresh(self, key: tuple) -> bool: ...
    def end_self_presentation_refresh(self, key: tuple) -> bool: ...
    def peer_session_scope_with_presentation_refresh(self, entry_channel: str, entry_utterance_id: UUID, session_scope: str | None, *, peer_presentation_refresh_burst: bool) -> str | None: ...
    def self_session_scope_with_presentation_refresh(self, entry_channel: str, entry_utterance_id: UUID, session_scope: str | None, *, primary_text: str, block_variant: str, self_presentation_refresh_burst: bool) -> str | None: ...
    @staticmethod
    def block_appearance_seq(appearance_seq: int | None, first_input_seq: int | None, last_updated_seq: int) -> int: ...


@runtime_checkable
class ExpirationEngineProtocol(Protocol):
    """Public API of ExpirationEngine — entry expiration."""

    def expire_entries(self, *, now: float, show_translation: bool, late_arrival_window_seconds: float, visible_ttl_seconds: float, self_translation_min_visible_seconds: float) -> bool: ...
    def entry_expiration_deadline(self, entry: object, *, show_translation: bool, late_arrival_window_seconds: float, visible_ttl_seconds: float, self_translation_min_visible_seconds: float) -> float | None: ...
    def entry_expiration_components(self, entry: object, *, show_translation: bool, late_arrival_window_seconds: float, visible_ttl_seconds: float, self_translation_min_visible_seconds: float) -> tuple[float | None, float | None, float | None]: ...


@runtime_checkable
class SelectionEngineProtocol(Protocol):
    """Public API of SelectionEngine — entry selection and visibility."""

    def visible_block_selection(self, *, entries: Mapping[tuple, object], live_self_entry: tuple[tuple, object] | None, live_peer_entry: tuple[tuple, object] | None, visible_window_target_blocks: int, show_translation: bool, show_peer_original: bool, peer_presentation_refresh_burst: bool, next_appearance_seq: object, self_presentation_refresh_burst: bool = ...) -> object: ...
    def entry_is_publishable(self, entry: object, *, show_peer_original: bool = ...) -> bool: ...
    def entry_is_selectable(self, entry: object, *, show_peer_original: bool = ...) -> bool: ...
    def _ensure_entry_visibility_metadata(self, entry: object, *, occupant_key: str, next_appearance_seq: object, publishable_seq: int | None = ...) -> None: ...


@runtime_checkable
class BlockRendererProtocol(Protocol):
    """Public API of BlockRenderer — presentation block building."""

    def build_presentation_block(self, entry: object, *, prefer_live_self: bool = ..., show_translation: bool, show_peer_original: bool, peer_presentation_refresh_burst: bool, self_presentation_refresh_burst: bool = ...) -> object | None: ...
    def rendered_block_signature(self, block: object) -> tuple[object, ...]: ...
    def rendered_blocks_signature(self, blocks: list) -> tuple[object, ...]: ...
    def visible_block_content_signature(self, block: object) -> tuple[str, str, str, bool]: ...
