"""Protocol definitions for pipeline mediator modules.

Each Protocol defines the public API of a pipeline module.
Modules depend on Protocols (hexagonal architecture), not on concrete implementations.
Pipeline (composition root) creates concrete implementations and wires them via DI.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, runtime_checkable
from uuid import UUID

if TYPE_CHECKING:
    from puripuly_heart.core.pipeline.channel_runtime import ChannelRuntime
    from puripuly_heart.core.pipeline.pipeline import Pipeline
    from puripuly_heart.domain.models import Transcript, Translation


@runtime_checkable
class PipelineContextProtocol(Protocol):
    """Public API of PipelineContext — shared state and utilities."""

    @property
    def llm(self) -> object: ...
    @property
    def translation_enabled(self) -> bool: ...
    @property
    def peer_translation_enabled(self) -> bool: ...
    @property
    def source_language(self) -> str: ...
    @property
    def target_language(self) -> str: ...
    @property
    def self_runtime(self) -> ChannelRuntime: ...
    @property
    def peer_runtime(self) -> ChannelRuntime: ...

    def _emit_basic(self, message: str, *args: object, level: int = ..., fallback_level: int | None = ...) -> None: ...
    def _emit_detailed(self, message: str, *args: object, level: int = ..., fallback_level: int | None = ...) -> bool: ...
    def _emit_metric(self, message: str, *args: object) -> None: ...


@runtime_checkable
class AudioMediatorProtocol(Protocol):
    """Public API of AudioMediator — STT event handling."""

    async def run_stt_event_loop(self, provider: object) -> None: ...
    async def stop_stt_task(self, attr_name: str, pipeline: Pipeline) -> None: ...
    async def reset_stt_runtime_state(self) -> None: ...
    async def handle_stt_event(self, event: object) -> None: ...
    def mark_promo_eligible(self) -> None: ...


@runtime_checkable
class VADHandlerProtocol(Protocol):
    """Public API of VADHandler — VAD event delegation."""

    def mark_resume_pending(self, event: object) -> None: ...
    def maybe_confirm_resume(self, event: object) -> object: ...
    def maybe_update_buffer_end_time(self, utterance_id: UUID) -> None: ...
    def maybe_start_finalize_wait(self, utterance_id: UUID) -> None: ...
    async def maybe_clear_resume_on_end(self, event: object) -> None: ...
    def record_peer_speech_end(self, utterance_id: UUID, speech_end_at: float) -> None: ...


@runtime_checkable
class LifecycleManagerProtocol(Protocol):
    """Public API of LifecycleManager — start/stop/replace."""

    async def start(self, pipeline: Pipeline, *, auto_flush_osc: bool = ...) -> None: ...
    async def stop(self, pipeline: Pipeline) -> None: ...
    async def replace_stt_provider(self, pipeline: Pipeline, stt: object) -> None: ...
    async def replace_peer_stt_provider(self, pipeline: Pipeline, stt: object) -> None: ...


@runtime_checkable
class TranscriptMediatorProtocol(Protocol):
    """Public API of TranscriptMediator — transcript handling."""

    async def submit_text(self, text: str, *, source: str = ...) -> UUID: ...
    async def handle(self, transcript: Transcript, *, is_final: bool, source: str | None) -> None: ...
    async def handle_peer_final(self, transcript: Transcript, parent_utterance_id: UUID, *, source: str) -> None: ...


@runtime_checkable
class TranslationExecutorProtocol(Protocol):
    """Public API of TranslationExecutor — translation execution."""

    async def ensure_translation(self, transcript: Transcript) -> None: ...
    async def translate_text(self, utterance_id: UUID, text: str, *, record_latency: bool = ...) -> Translation: ...
    async def translate_and_enqueue(self, utterance_id: UUID, text: str, *, runtime: ChannelRuntime | None = ...) -> None: ...


@runtime_checkable
class TranslationLoggerProtocol(Protocol):
    """Public API of TranslationLogger — translation logging."""

    def skip_reason(self, runtime: ChannelRuntime) -> str: ...
    def log_skipped(self, *, stage: str, runtime: ChannelRuntime, publish_chatbox: bool) -> None: ...
    def log_failure(self, *, stage: str, runtime: ChannelRuntime, exc: Exception, detailed: bool = ...) -> None: ...
    def emit_ready(self, *, translation: Translation, runtime: ChannelRuntime) -> bool: ...


@runtime_checkable
class OutputMediatorProtocol(Protocol):
    """Public API of OutputMediator — OSC output."""

    async def enqueue_osc(self, utterance_id: UUID, *, transcript_text: str, translation_text: str | None) -> None: ...
    def enqueue_peer_translation_disclosure(self, text: str) -> None: ...
    def set_typing_reason(self, reason: str, active: bool) -> None: ...
    def clear_typing_reasons(self) -> None: ...
    async def run_flush_loop(self) -> None: ...


@runtime_checkable
class PeerTurnTrackerProtocol(Protocol):
    """Public API of PeerTurnTracker — peer logical-turn bookkeeping."""

    def clear_state(self) -> None: ...
    def on_peer_speech_end(self, utterance_id: UUID, speech_end_at: float) -> None: ...
    def complete_peer_logical_turn(self, peer_turn_id: UUID, *, preserve_parent_speech_end_time: bool = ...) -> None: ...
    def peer_logical_turn_transcript(self, transcript: Transcript) -> tuple[UUID, Transcript]: ...


@runtime_checkable
class OverlayEmitterProtocol(Protocol):
    """Public API of OverlayEmitter — overlay event emission."""

    async def emit_final_transcript_to_overlay(self, transcript: Transcript) -> None: ...
    async def finalize_peer_source_only(self, transcript: Transcript, *, close_is_final: bool, finalize_latency: bool, preserve_parent_speech_end_time: bool = ...) -> None: ...
    async def emit_overlay_utterance_closed(self, *, utterance_id: UUID, channel: object, is_final: bool) -> None: ...
    def finalize_latency_for_utterance(self, *, utterance_id: UUID, channel: object, finalize_latency: bool | None = ...) -> None: ...
    async def emit_overlay_utterance_closed_with_latency(self, *, utterance_id: UUID, channel: object, is_final: bool, finalize_latency: bool | None = ...) -> None: ...
    async def emit_translation_to_overlay(self, *, translation: Translation, applied_context_mode: object | None) -> None: ...
    async def emit_peer_translation_to_overlay(self, *, translation: Translation, runtime: object, applied_context_mode: object | None) -> None: ...
    async def emit_self_active_overlay_event(self, event: object) -> None: ...
    def overlay_translation_will_follow(self, runtime: object) -> bool: ...
    def peer_terminal_work_will_follow(self, runtime: object) -> bool: ...
    async def sync_overlay_active_self(self, buffer: object, *, created_at: float | None = ...) -> None: ...
    async def reset_overlay_preview(self) -> None: ...
    def _self_overlay_languages_for_utterance(self, utterance_id: UUID) -> tuple[str, str]: ...
    def _active_self_occupant_key(self, buffer: object) -> str: ...
    def should_blank_stale_active_secondary_before_finalizing(self, *, final_text: str, reuse_mode: str | None) -> bool: ...


@runtime_checkable
class BufferManagerProtocol(Protocol):
    """Public API of BufferManager — low-latency merge buffer management.

    All methods are underscore-prefixed because BufferManager is an internal
    module consumed only by VADHandler and AudioMediator within the pipeline.
    """

    def _mark_resume_pending(self, event: object) -> None: ...
    def _maybe_confirm_resume(self, event: object) -> object: ...
    def _maybe_update_buffer_end_time(self, utterance_id: object) -> None: ...
    def _maybe_start_finalize_wait(self, utterance_id: object) -> None: ...
    async def _maybe_clear_resume_on_end(self, event: object) -> None: ...
    async def _handle_low_latency_final(self, transcript: object) -> None: ...
