from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from collections.abc import Callable

    from puripuly_heart.config.settings import AppSettings

    OverlayStateFn = Callable[[AppSettings], AppSettings] | None


class SettingsDraftServiceProtocol(Protocol):
    """Structural contract for SettingsDraftService — used by core/ and ui/."""

    @property
    def has_provider_changes(self) -> bool: ...

    @has_provider_changes.setter
    def has_provider_changes(self, value: bool) -> None: ...

    @property
    def has_pending_prompt_changes(self) -> bool: ...

    @has_pending_prompt_changes.setter
    def has_pending_prompt_changes(self, value: bool) -> None: ...

    @property
    def _provider_settings_draft(self) -> AppSettings | None: ...

    @_provider_settings_draft.setter
    def _provider_settings_draft(self, value: AppSettings | None) -> None: ...

    def set_settings(self, settings: AppSettings) -> None: ...
    def reset(self) -> None: ...
    def copy_provider_draft_fields(self, source: AppSettings, target: AppSettings) -> None: ...
    def build_settings_with_provider_draft(self) -> AppSettings | None: ...
    def sanitize_provider_apply_settings(self, settings: AppSettings | None) -> AppSettings | None: ...
    def stage_prompt_draft(self, value: str) -> None: ...
    def committed_prompt_value(self) -> str: ...
    def build_provider_apply_settings(self, overlay_state_fn: OverlayStateFn = None) -> AppSettings | None: ...
    def consume_provider_apply_settings(self, overlay_state_fn: OverlayStateFn = None) -> AppSettings | None: ...
    def consume_prompt_apply_settings(self, overlay_state_fn: OverlayStateFn = None) -> AppSettings | None: ...
    def _ensure_provider_settings_draft(self) -> AppSettings: ...

