from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from puripuly_heart.config.settings import AppSettings


class AppSettingsProtocol(Protocol):
    """Minimal structural contract for AppSettings — used by core/ for type checking.

    NOTE: This is intentionally partial. Only fields commonly accessed in core/
    are listed. The concrete AppSettings dataclass in config.settings has more fields.
    """

    @property
    def provider(self) -> object: ...
    @property
    def translation(self) -> object: ...
    @property
    def languages(self) -> object: ...
    @property
    def audio(self) -> object: ...
    @property
    def desktop_audio(self) -> object: ...
    @property
    def overlay(self) -> object: ...
    @property
    def stt(self) -> object: ...
    @property
    def local_llm(self) -> object: ...
    @property
    def llm(self) -> object: ...
    @property
    def osc(self) -> object: ...
    @property
    def ui(self) -> object: ...
    @property
    def backup_translation(self) -> object: ...
    @property
    def system_prompt(self) -> str: ...
