"""Protocol definitions for STT leaf modules.

Leaf modules are independently-owned-state helpers consumed by ManagedSTTProvider.
stt_log_sink, stt_audio_diagnostics, stt_pending_tracker are true leaves.
stt_hallucination_filter has bidirectional dependency with controller (TYPE_CHECKING guard).
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol
from uuid import UUID

if TYPE_CHECKING:
    import numpy as np


class STTLogSinkProtocol(Protocol):
    """Logging adapter for STT session events."""
    def basic(self, message: str, *args: object, level: int = ..., fallback_level: int | None = ...) -> None: ...
    def detailed(self, message: str, *args: object, level: int = ...) -> None: ...
    def audio_diag_detailed(self, message: str, *args: object, level: int = ...) -> None: ...
    def log_session_connected(self, *, attempts: int) -> None: ...


class AudioDiagnosticsProtocol(Protocol):
    """Audio quality diagnostics and fault detection."""
    def reset_for_utterance(self) -> None: ...
    def current_fault_profile(self) -> object: ...
    def process_input(self, samples_f32: object) -> np.ndarray: ...
    def emit_for_utterance(self, utterance_id: UUID, *, finalize: bool) -> None: ...


class PendingTrackerProtocol(Protocol):
    """Tracks utterances between speech-end and final-transcript arrival."""
    def append(self, utterance_id: UUID, ended_at: float) -> None: ...
    def pop_next_final(self) -> UUID | None: ...
    def peek_first(self) -> UUID | None: ...
    def drop_stale(self, *, has_active_utterance: bool = ...) -> None: ...
    def check_finalization_lag(self, *, utterance_id: UUID | None, pending_queue_size_before: int, text_len: int) -> None: ...
    def has_pending(self) -> bool: ...
    def size(self) -> int: ...
    def clear(self) -> None: ...
